<div id="bottom_section">
	<script type="text/javascript">
	<!--
		google_ad_client = "ca-pub-6292354213615229";
		/* bottombar */
		google_ad_slot = "2289491429";
		google_ad_width = 728;
		google_ad_height = 90;
	//-->
	</script>
	<script type="text/javascript"
		//src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
	</script>
</div>
<div id="footer">
    <div class="left_footer">
        &copy; Copyright 2010 &nbsp;&nbsp;&nbsp;<a href="/"><?php echo WebSiteName;?></a>
        &nbsp;&nbsp;|&nbsp;&nbsp;<a href="<?php echo 'mailto:'.ContactEmail;?>">Contact me</a>
    </div>
    <div id="right_footer">
        &copy; Powered by &nbsp;&nbsp;&nbsp;<a href="/"><?php echo WebSiteName;?></a>
        &nbsp;&nbsp;|&nbsp;&nbsp;<a href="<?php echo 'mailto:'.ContactEmail;?>">Contact me</a>
    </div>
</div>
	   </div>
</center>
				<script type="text/javascript">
				<!--	
					function makeArray() {
						for (i = 0; i<makeArray.arguments.length; i++)
							this[i + 1] = makeArray.arguments[i];
					}

					var months = new makeArray('January','February','March','April','May',
						'June','July','August','September','October','November','December');
					var date = new Date();
					var day = date.getDate();
					var month = date.getMonth() + 1;
					var yy = date.getYear();
					var year = (yy < 1000) ? yy + 1900 : yy;
					var s= months[month]+" , "+ day  + " , " + year;
					//document.getElementById("cur_date").innerHTML=s;
					document.body.bgColor="lavender";
				//-->				
				</script>

</body>
</html>

